# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jH1-c3GUkFpivbCDl6t8-fiuC2kHdfhv
"""

import numpy as np


matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])


transposed_matrix = matrix.T

print(transposed_matrix)

